ANNOT_KEY = '/Annots'
ANNOT_FIELD_KEY = '/T'
ANNOT_VAL_KEY = '/V'
ANNOT_RECT_KEY = '/Rect'
SUBTYPE_KEY = '/Subtype'
WIDGET_SUBTYPE_KEY = '/Widget'
ROOT_PATH = '/opt/pdf-generator'
MAPPING_FILE_PATH = f'{ROOT_PATH}/mapping.json'
