all:
	rm -r  27-compliant/*
	py-backwards -i *.py -o 27-compliant/ -t 2.7
	cp *.pdf 27-compliant/
	cp *.php 27-compliant/
	cp mapping.json 27-compliant/

clean:
	rm -r 27-compliant/*

build:
	py-backwards -i *.py -o 27-compliant/ -t 2.7
	cp *.pdf 27-compliant/
	cp *.php 27-compliant/
	cp mapping.json 27-compliant/


